title: UC Santa Cruz Notable Women
email: ttran34@ucsc.edu
description: >- # this means to ignore newlines until "baseurl:"
  This International Women's Day, we are lifting up the achievements of 35 phenomenal UC Santa Cruz women. From astronomers and astronauts to activists, journalists, judges, and so much more, these women are trailblazers, and many have been "firsts" in their fields. For us, these women exemplify the words immortalized by the poet Maya Angelou: "I’m a woman / Phenomenally. / Phenomenal woman, / That’s me."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://women.ucsc.edu" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ucsantacruz
github_username:  ucsc

# Build settings
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-assets

# Structure configuration
source: ./source
destination: ./build

# Build Settings
markdown: kramdown
kramdown:
  auto_ids: false

include: ['_pages']

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
