[[redirects]]
  from = "/faber"
  to = "https://women.ucsc.edu/index.html#faber"
  status = 301

[[redirects]]
  from = "/kuttner"
  to = "https://women.ucsc.edu/index.html#kuttner"
  status = 301

[[redirects]]
  from = "/erendirasandoval"
  to = "https://women.ucsc.edu/index.html#erendirasandoval"
  status = 301

[[redirects]]
  from = "/mendoza"
  to = "https://women.ucsc.edu/index.html#mendoza"
  status = 301

[[redirects]]
  from = "/davis"
  to = "https://women.ucsc.edu/index.html#davis"
  status = 301

[[redirects]]
  from = "/packard"
  to = "https://women.ucsc.edu/index.html#packard"
  status = 301

[[redirects]]
  from = "/anderson"
  to = "https://women.ucsc.edu/index.html#anderson"
  status = 301

[[redirects]]
  from = "/black"
  to = "https://women.ucsc.edu/index.html#black"
  status = 301

[[redirects]]
  from = "/schatz"
  to = "https://women.ucsc.edu/index.html#schatz"
  status = 301

[[redirects]]
  from = "/batalha"
  to = "https://women.ucsc.edu/index.html#batalha"
  status = 301

[[redirects]]
  from = "/rich"
  to = "https://women.ucsc.edu/index.html#rich"
  status = 301

[[redirects]]
  from = "/sullivan"
  to = "https://women.ucsc.edu/index.html#sullivan"
  status = 301

[[redirects]]
  from = "/hooks"
  to = "https://women.ucsc.edu/index.html#hooks"
  status = 301

[[redirects]]
  from = "/shapiro"
  to = "https://women.ucsc.edu/index.html#shapiro"
  status = 301

[[redirects]]
  from = "/silver"
  to = "https://women.ucsc.edu/index.html#silver"
  status = 301

[[redirects]]
  from = "/aptheker"
  to = "https://women.ucsc.edu/index.html#aptheker"
  status = 301

[[redirects]]
  from = "/perry"
  to = "https://women.ucsc.edu/index.html#perry"
  status = 301

[[redirects]]
  from = "/omidyar"
  to = "https://women.ucsc.edu/index.html#omidyar"
  status = 301

[[redirects]]
  from = "/perez"
  to = "https://women.ucsc.edu/#perez"
  status = 301

[[redirects]]
  from = "/grande"
  to = "https://women.ucsc.edu/#grande"
  status = 301

[[redirects]]
  from = "/scott"
  to = "https://women.ucsc.edu/#scott"
  status = 301

[[redirects]]
  from = "/greenwood"
  to = "https://women.ucsc.edu/#greenwood"
  status = 301

[[redirects]]
  from = "/priest"
  to = "https://women.ucsc.edu/#priest"
  status = 301

[[redirects]]
  from = "/nguyen"
  to = "https://women.ucsc.edu/#nguyen"
  status = 301

[[redirects]]
  from = "/gerhardt"
  to = "https://women.ucsc.edu/#gerhardt"
  status = 301

[[redirects]]
  from = "/madison"
  to = "https://women.ucsc.edu/#madison"
  status = 301

[[redirects]]
  from = "/wojcicki"
  to = "https://women.ucsc.edu/#wojcicki"
  status = 301

[[redirects]]
  from = "/mcnutt"
  to = "https://women.ucsc.edu/#mcnutt"
  status = 301

[[redirects]]
  from = "/voeltz"
  to = "https://women.ucsc.edu/#voeltz"
  status = 301

[[redirects]]
  from = "/moglen"
  to = "https://women.ucsc.edu/#moglen"
  status = 301

[[redirects]]
  from = "/geha"
  to = "https://women.ucsc.edu/#geha"
  status = 301

[[redirects]]
  from = "/jackson"
  to = "https://women.ucsc.edu/#jackson"
  status = 301

[[redirects]]
  from = "/langeheim"
  to = "https://women.ucsc.edu/#langeheim"
  status = 301

[[redirects]]
  from = "/rudolph"
  to = "https://women.ucsc.edu/#rudolph"
  status = 301

[[redirects]]
  from = "/maechler"
  to = "https://women.ucsc.edu/#maechler"
  status = 301
