[[redirects]]
  from = "/faber"
  to = "https://women.ucsc.edu/#faber"
  status = 200

[[redirects]]
  from = "/kuttner"
  to = "https://women.ucsc.edu/#kuttner"
  status = 200

[[redirects]]
  from = "/eréndirasandoval"
  to = "https://women.ucsc.edu/#eréndirasandoval"
  status = 200

[[redirects]]
  from = "/mendoza"
  to = "https://women.ucsc.edu/#mendoza"
  status = 200

[[redirects]]
  from = "/davis"
  to = "https://women.ucsc.edu/#davis"
  status = 200

[[redirects]]
  from = "/packard"
  to = "https://women.ucsc.edu/#packard"
  status = 200

[[redirects]]
  from = "/anderson"
  to = "https://women.ucsc.edu/#anderson"
  status = 200

[[redirects]]
  from = "/black"
  to = "https://women.ucsc.edu/#black"
  status = 200

[[redirects]]
  from = "/schatz"
  to = "https://women.ucsc.edu/#schatz"
  status = 200

[[redirects]]
  from = "/batalha"
  to = "https://women.ucsc.edu/#batalha"
  status = 200

[[redirects]]
  from = "/rich"
  to = "https://women.ucsc.edu/#rich"
  status = 200

[[redirects]]
  from = "/sullivan"
  to = "https://women.ucsc.edu/#sullivan"
  status = 200

[[redirects]]
  from = "/hooks"
  to = "https://women.ucsc.edu/#hooks"
  status = 200

[[redirects]]
  from = "/shapiro"
  to = "https://women.ucsc.edu/#shapiro"
  status = 200

[[redirects]]
  from = "/silver"
  to = "https://women.ucsc.edu/#silver"
  status = 200

[[redirects]]
  from = "/aptheker"
  to = "https://women.ucsc.edu/#aptheker"
  status = 200

[[redirects]]
  from = "/perry"
  to = "https://women.ucsc.edu/#perry"
  status = 200

[[redirects]]
  from = "/omidyar"
  to = "https://women.ucsc.edu/#omidyar"
  status = 200

[[redirects]]
  from = "/perez"
  to = "https://women.ucsc.edu/#perez"
  status = 200

[[redirects]]
  from = "/grande"
  to = "https://women.ucsc.edu/#grande"
  status = 200

[[redirects]]
  from = "/scott"
  to = "https://women.ucsc.edu/#scott"
  status = 200

[[redirects]]
  from = "/greenwood"
  to = "https://women.ucsc.edu/#greenwood"
  status = 200

[[redirects]]
  from = "/priest"
  to = "https://women.ucsc.edu/#priest"
  status = 200

[[redirects]]
  from = "/nguyen"
  to = "https://women.ucsc.edu/#nguyen"
  status = 200

[[redirects]]
  from = "/gerhardt"
  to = "https://women.ucsc.edu/#gerhardt"
  status = 200

[[redirects]]
  from = "/madison"
  to = "https://women.ucsc.edu/#madison"
  status = 200

[[redirects]]
  from = "/wojcicki"
  to = "https://women.ucsc.edu/#wojcicki"
  status = 200

[[redirects]]
  from = "/mcnutt"
  to = "https://women.ucsc.edu/#mcnutt"
  status = 200

[[redirects]]
  from = "/voeltz"
  to = "https://women.ucsc.edu/#voeltz"
  status = 200

[[redirects]]
  from = "/moglen"
  to = "https://women.ucsc.edu/#moglen"
  status = 200

[[redirects]]
  from = "/geha"
  to = "https://women.ucsc.edu/#geha"
  status = 200

[[redirects]]
  from = "/jackson"
  to = "https://women.ucsc.edu/#jackson"
  status = 200

[[redirects]]
  from = "/langeheim"
  to = "https://women.ucsc.edu/#langeheim"
  status = 301

[[redirects]]
  from = "/rudolph"
  to = "https://women.ucsc.edu/#rudolph"
  status = 301

[[redirects]]
  from = "/maechler"
  to = "https://women.ucsc.edu/#maechler"
  status = 301
